### ISSUE TITLE
Facebook Login is not working

### ISSUE THREAD

**Issue by forthright48** [bologer/anycomment.io#127]
So I completed the setup for login with FB. I am kind of sure I did things correctly because I was able to make "Super Socializer" work, but not anycomment.

When I click on quick login below the comment box, it takes me to a page on facebook where it asks for permission to connect. I give the permission. And then the page refreshes.

Next, if I try to comment, it gives error saying: "Please use any of the available social networks to leave a comment".

If I try to login pressing the fb icon again, the page just refreshes. That's it.

So overall, the fb login is not working for some reason.

**Comment by bologer** [comment]
Hello, 

> When I click on quick login below the comment box, it takes me to a page on facebook where it asks for permission to connect. I give the permission. And then the page refreshes.

Do you have some WordPress user (possibly your admin account) under the same email as the FB account?

> Next, if I try to comment, it gives error saying: "Please use any of the available social networks to leave a comment".

Are you logged in at this point or trying to leave comment as a guest? 
 
What type of form did you choose in the admin? 
Is it for guest  + social authorization or just guest?

**Comment by forthright48** [comment]
> Do you have some WordPress user (possibly your admin account) under the same email as the FB account?

Yes. My admin account has same email as my fb account.

> Are you logged in at this point or trying to leave comment as a guest?

I am not logged in. It doesn't show my face on comment box.

> What type of form did you choose in the admin? Is it for guest + social authorization or just guest?

I have "Users must be registered and logged in to comment" checked in. Guest commenting is not allowed.

**Comment by forthright48** [comment]
Ok. I tried to add Google login. 

Same as before. Clicking the icon takes me to a page. Inserted my credential. Then it showed error. The classic HTTP ERROR 500 Page.

If I go back to my site and try to login again to Google, this time, it doesn't ask for credential any more. It takes me to ERROR 500 page of chrome (as shown below), and the URL in bar at that moment is "https://forthright48.com/wp-json/anycomment/v1/auth/google?redirect=https://forthright48.com/2018/01/prufer-code-linear-representation-of-a-labeled-tree.html"

![image](https://user-images.githubusercontent.com/7130525/45040068-afc0d280-b097-11e8-917f-a0a8b3c0e562.png)

**Comment by bologer** [comment]
@forthright48 btw, I can notice some performance issue when sending a comment. 

What server environment do you have? 

I ask because I have some basic hosting on some of the my websites and it takes about 800 ms to send a comment. But when I send comment on your blog, it seems to be about 2-3 seconds. It will be good to investigate on this, I would like to actually find out why this happens and possibly fix if issue is on the plugin side.

**Comment by forthright48** [comment]
@bologer 

> Sorry, but at the moment we cannot handle the situation when emails collide. This could only happen in case when you register and then trying to login via social network which has the same email address.

Ok. I understand. This raises a new question. If I login using facebook with xyz email, then I can't login with google using the same xyz email? 

> not sure about Google issue, could you provide more information? What exactly are you trying to do? Did it ask you permissions first and then redirected back to the website and shown 500? Or 500 happens before permissions were asked?

The first time when I clicked it, it asked for permission. Once I gave all the permissions, it redirected back to my website and gave 500 error. From there on, whenever I click on Google login, it redirects and shows me 500 error (doesn't ask for permission anymore.

> Do you use the same email in Google as you do for admin? Maybe it is somehow related to the issue I described in here.

Yes. I use the same email.

> What server environment do you have?

I am using the starter pack from this [site](https://www.dhrubohost.com/web_hosting.php). I recently migrated from blogger to WP. Still new with this platform, so yeah, there are probably tons mistakes I am making.

Anyways, I logged in to my wordpress blog using the tradition website.com/wp-login url and I can now comment. So that's enough for me. 

But can my readers use multiple logins? That is, if one has example@gmail.com email and logs in using facebook and makes a comment. Then can he comment again using Google login this time. Will the system consider both comments coming from same person or will it consider different? If it considers the same person, then there is no issue. I can live with this.

**Comment by bologer** [comment]
@forthright48 was testing Google and it seems that it works on my local set-up. I will try it also on my own blog, will give you some results in about 10 minutes. 

Could you provide some error logs?
Should be something like error.log or something

**Comment by bologer** [comment]
@forthright48 checked on personal blog, it seems to be wroking just fine. Try [this one](http://bologer.ru/anycomment-chto-ozhidat-v-versii-0-0-45). Let me know if it works for you on my blog. If does,  we should figure out why it does not work on your website.

**Comment by bologer** [comment]
@forthright48 hm, try it like this bologer.ru/wp-login.php?action=logout

**Comment by bologer** [comment]
@forthright48 closing this as I see no problem with Facebook. 

Could you please reopen a new issue regarding Google 500 error if you will still have on the plugin update? Just link new one with this one, once created.


It will be rolled out in about an hour.
