### ISSUE TITLE
Default WordPress Login 

### ISSUE THREAD

**Issue by forthright48** [bologer/anycomment.io#131]
You almost have all the social sites, but what about the normal wordpress login? I am talking about this:

![image](https://user-images.githubusercontent.com/7130525/45164002-1ecb3200-b224-11e8-908f-18b45d11fa71.png)

Is it possible to add a WordPress icon in quick login, pressing which takes you to the normal login page which is located at "/wp-login.php".

From there, an user can login normally.

This has an interesting side effect. As you can see in the pic above, I happen to have social login buttons on the normal wordpress login page. It comes from another plugin I use. This one currently handles the case of multiple social site using single email address properly. So no matter which social login user uses, as long as the email is same, they are all considered same user.

So by combining the two plugins I can have a comment system where user can login using multiple social logins. It's just a workaround until you intergreate the feature into the comment system in some future version.

**Comment by bologer** [comment]
@forthright48 do they create a new user when email is matching with already existing user or just log him in as the initial user?

Question:
>  I am admin, have `x` email, I logout, and login via facebook that has `x` email. Would plugin log me in as admin or as facebook user? 

I will make this integration in the next release, which expected to be on Monday.  

I would like also to add social icons on login page, as it shouldn't be really difficult thing to do.

**Comment by forthright48** [comment]
@bologer : They log him in as the initial user. They create new user only if email address is missing in the database.

> I am admin, have x email, I logout, and login via facebook that has x email. Would plugin log me in as admin or as facebook user?

They login me as admin.

**Comment by bologer** [comment]
@forthright48 I see. This is nice, but probably good idea is to connect all of the users and their accounts. 
I will figure out how to make it, leaving the choice for admin how it should be handled.

**Comment by bologer** [comment]
@forthright48 I will move this feature for the upcoming Thursday as had no time for it yet, however I managed for now make a fix for same user email. For now, user who has the same email will be logged in as an existing user. 

E.g. admin has email `x`, you login using FB under `x` email, you will be logged in as admin. 

Another example, I logged in via google under `x`, and users logs in via FB under `x`, he will be logged in as Google user.  

This is just for the time being, on 0.0.56 I will make multi account support, did not really have much time to work on this, was focused on other related issues.

**Comment by bologer** [comment]
Hey @forthright48 , 

New version is release, WordPress icon is now in the list of social icons :) 

Clicking on it will redirect to default WordPress login form and on success should return back to comments. 

Btw, we have other cool changes, see the changelog. 

Comments should now load x2 faster :)
