### ISSUE TITLE
New error every time page refreshed on admin site

### ISSUE THREAD

**Issue by forthright48** [bologer/anycomment.io#132]
Every time I refresh my a page on the backend (admin site), a new error gets logged in. 

This is the error:

```
Notice: Undefined index: page in /home/forthrig/public_html/wp-content/plugins/anycomment/includes/admin/AnyCommentAdminPages.php on line 99
```

It's filling up my error log.

![image](https://user-images.githubusercontent.com/7130525/45174216-d8ce9800-b23c-11e8-9f2d-bc0fa7106a5b.png)

**Comment by bologer** [comment]
@forthright48 thanks. 

This is not really error but a notice. But anyways, this is good to know and I will fix it in the next release :)
