### ISSUE TITLE
Check Safari problem, some user unable to save settings form

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#159]
Safari version: 

```
Версия 12.0 (14606.1.36.1.9)
```

More info: 

```
когда жму Сохранить, в консоле: An invalid form control with name='anycomment-generic[options_files_max_size]' is not focusable.
```

Issue described [here](https://stackoverflow.com/a/28340579/3661795)

**Comment by bologer** [comment]
@mihdan есть возможность как-то на сафари чекнуть? или может быть у кого-то у знакомых есть мак? У меня на минте вообще не поставить это чудо, только через вайн exe запускать видимо)

**Comment by bologer** [comment]
@mihdan суть в том, что пользователя не могут сохранить форму в "Настройки" никак. Толком не могу понять что этому может мешать. Так же не могут вкключить поцию "Включить комментарии", по словам кто репортил пишут, что не ставится вовсе.

**Comment by mihdan** [comment]
Я попробую через браузестек проверить на своем сайте

**Comment by mihdan** [comment]
Я спросил у реальныйх сафари-юзеров - баг есть и самый простой способ это отключение валидации

**Comment by bologer** [comment]
@mihdan типо `novalidate` на форме?

**Comment by mihdan** [comment]
Да @bologer
