### ISSUE TITLE
Не скинулся кеш

### ISSUE THREAD

**Issue by mihdan** [bologer/anycomment.io#216]
Добавил новый комментарий через сайт под сатьей
Его нет на сайте после рефреша - http://screenshot.kobzarev.com/2018-10-15-1539598539.png
Но он есть в админке - http://screenshot.kobzarev.com/2018-10-15-1539598634.png
При этом в инкогнито показываются http://screenshot.kobzarev.com/2018-10-15-1539599068.png
Но не работает эмбед с ютюба

Версия 0.0.61
WordPress 4.9.8

**Comment by bologer** [comment]
Я временно отключил кеширование у плагина, проблема точно не в этом. Может ли быть что у тебя стоит отдельное кеширование которое делает такое?

**Comment by mihdan** [comment]
У меня есть wp-rocket, но он не работает когда залогинен, особенно когда под админом, мож что у хостера, проверим

**Comment by bologer** [comment]
@mihdan проверь пожалуйста. По сути должно работать, так как кеширования сейчас уже нет. Напиши мне потом о результатах

**Comment by bologer** [comment]
@mihdan проверь пожалуйста после релиза и если все ок, то можешь закрывать ее

**Comment by mihdan** [comment]
Всё чётко теперь, спасибо
