### ISSUE TITLE
Отсутствует анимация отправки комментария

### ISSUE THREAD

**Issue by artikus11** [bologer/anycomment.io#218]
При нажатии кнопки Отправить, нет никого визуального сопровождения и потому непонятно ушел комент или нет. Что приводит к дублированию комментариев

Надо или анимацию сделать или сообщение об отправке выводить

**Comment by mihdan** [comment]
@artikus11 а у тебя при этом очищается поле ввода и новый коммент встает на место под статьей или вообще ничего не видно?

**Comment by bologer** [comment]
@mihdan он  имеет ввиду, когда ты отправляешь комментарий и потом сразу же пытаешься еще раз нажать. Из-за этого часто получается, что комментарии дублируются.

**Comment by artikus11** [comment]
@mihdan Вон @bologer правильно сказал. 

Написал комментарий, жму на Отправить, А ничего не происходит. Жму еще раз, о-па, комент в ленте появился 2 раза))

**Comment by mihdan** [comment]
Актуально особенно когда много комментов и они по возрастанию стоят - новые внизу. Просто не видно , что он туда добавился
