### ISSUE TITLE
Шрифты в комментариях

### ISSUE THREAD

**Issue by artikus11** [bologer/anycomment.io#221]
Непонятно зачем плагин загружает собственные шрифты? Комментарии как система не могут отдельно от сайта и конкретной статьи существовать. А значит и шрифты в них должны быть родные от сайта. 

Понятно что есть настройка для изменения, но зачем менять, если можно просто эту опцию не делать? Ну просто по дефолту берется родной шрифт сайта, если надо изменить меняется через css, ну или через опцию

**Comment by bologer** [comment]
Старый тикет, но сейчас решил пройтись по всем тикетам. 

На данный момент, если в настройках изменить шрифт со стандартного на свой, тогда Google шрифт не будет подгружаться. 

Думаю, что это вполне нормальное решение. 

У нас уже есть [тикет](https://github.com/bologer/anycomment.io/issues/140), где в будущем запланирован выборщик шрифтов от гугла, но это не сильно относится к этому тикету.
