### ISSUE TITLE
Предотвращение кеширования запросов по REST API

### ISSUE THREAD

**Issue by mihdan** [bologer/anycomment.io#224]
Сейчас запрос на получение комментариев для поста выглядит следующим образом:

`/wp-json/anycomment/v1/comments?post=8088&parent=0&per_page=20&order=asc&order_by=id`

Если по пути от юзера к сайту есть прокси-сервер или юзер подключен по VPN, возможно кеширование данного запроса, чтобы этого не происходило, можно добавлять в конец запроса случайный параметр, чтобы URL выглядил постоянно уникальным для предотвращения кеширования.

Например так:

`wp-json/anycomment/v1/comments?post=8088&parent=0&per_page=20&order=asc&order_by=id&rnd=<?php echo time(); ?>`

**Comment by bologer** [comment]
Я бы еще добавил опцию для этого. Так как не у всех стоит кеширование и кому-то это не пригодиться.

**Comment by bologer** [comment]
@mihdan создал отдельную issue по поводу [вот этого](https://github.com/bologer/anycomment.io/issues/224#issuecomment-430499609), эту issue можешь тоже закрыть если проблема будет решена

**Comment by mihdan** [comment]
Последний релиз решил проблему
