### ISSUE TITLE
Замечания к релизу 0.0.65

### ISSUE THREAD

**Issue by artikus11** [bologer/anycomment.io#249]
- [x] Лишние отступы. Вот так должно быть 
![image](https://user-images.githubusercontent.com/16116688/47288551-a2d84e00-d607-11e8-9435-2f96fdb7c254.png)
```
#anycomment-root {
    display: flex;
    flex-grow: 1;
    flex-direction: column;
    padding: 1rem 0;
    position: relative;
}
```

- [x] При добавлении бордер-радиуса для кнопки он меняется не только у кнопки, но еще и у других элементов.
 ![image](https://user-images.githubusercontent.com/16116688/47288618-eb900700-d607-11e8-986c-f59ff3e99e4f.png)

- [x] Комментарий не всегда оборачивается абзацем ![image](https://user-images.githubusercontent.com/16116688/47288636-08c4d580-d608-11e8-867c-07d0a9c0b590.png)
Добавить стили 
```
#anycomment-root .anycomment-list .comment-single-body__text-content {
line-height: 1.6;
}
```

- [x] Исправить размер иконок
![image](https://user-images.githubusercontent.com/16116688/47288709-475a9000-d608-11e8-81f5-e9d40f2302c0.png)
Иначе при изменении размера шрифтов начинаются пляски
```
#anycomment-root .anycomment-social {
width: 30px;
height: 30px;
line-height: 31px;
}
```

- [x] Необходимо как-то помечать коментарии на фронте, которые на модерации, а то непонятно. В статье админ комент видит, а реально его на странице нет, так как он на модерации

- [x] В ссылку на плагин поставить nofollow и было бы неплохо дать возможность изменять текст в этой ссылке. Я бы написал "Коментарии на сайте работают на..."
![image](https://user-images.githubusercontent.com/16116688/47303854-198c4000-d636-11e8-94a6-3743e295756f.png)

- [x] При изменении комментария, надо формой подменять изменяемый текст, а то я сначала в текст тыкаю, а потом форму вижу

- [x] При изменении комментария в форме остается старый текст, надо его как-то сбрасывать
![image](https://user-images.githubusercontent.com/16116688/47304292-35dcac80-d637-11e8-9136-633e253b5936.png)

**Comment by bologer** [comment]
@artikus11 можешь плиз пояснить, что ты имеешь ввиду под: 

>  При изменении комментария, надо формой подменять изменяемый текст, а то я сначала в текст тыкаю, а потом форму вижу

**Comment by artikus11** [comment]
@bologer Вот смотри
![ashampoo_snap_2018 10 26_14h39m07s_038_](https://user-images.githubusercontent.com/16116688/47562110-7cc7ec00-d92e-11e8-8b6d-6afa899780b6.gif)

При нажатии изменить форма появляется под изменяемым комментарием. Не всегда это понятно.
Надо или при появлении формы после нажатия как-то затенять текст исходного комментария или форму прямо поверх вызывать

**Comment by artikus11** [comment]
@bologer ТОгда надо визуализировать процесс изменения, чтобы при изменении в форме изменялся бы и исходный комент. Но проще заблюрить, тут @mihdan прав

**Comment by bologer** [comment]
Перенес пункт с изменением в #248
