### ISSUE TITLE
Add "CPT UI" to the list of conflict ones 

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#252]
Плагин CPT UI в параметре (Show in REST API) true нужно установить

**Comment by mihdan** [comment]
У этого плагина есть фильтры или о  какой проблеме речь?

**Comment by bologer** [comment]
@mihdan да, вот "Show in REST API", там переключатель (это как мне пользователь написал).

**Comment by bologer** [comment]
![image](https://user-images.githubusercontent.com/9879933/47875725-91692000-de17-11e8-8ee1-d0114e35e66e.png)
