### ISSUE TITLE
Индексирование комментов

### ISSUE THREAD

**Issue by mihdan** [bologer/anycomment.io#263]
Чтобы при использовании ajax пагинации боты индексировали комменты, нужно запугать в wp эндпоинт `comment-page`, например.

При переходе по нему должны выводится соответствующие страницу комментов.

При клике на панинатор в комментах нужно менять урл через pushState добавив наш эндпоинт.

Идея тут https://www.search-foresight.com/en/the-recommended-method-for-indexing-ajax-content-in-2018-search-foresight-publishes-a-demo/

**Comment by bologer** [comment]
@mihdan идея хорошая, думаю, что такое можно реализовать в этот понедельник. Я еще почитаю по этой теме, может найду еще какие-то детали или подводные камни. Если что-то еще интересное найдешь, кидай прямо сюда

**Comment by mihdan** [comment]
@bologer конечно

**Comment by bologer** [comment]
Some more resources: 
- https://support.google.com/webmasters/answer/1663744?hl=en
- https://www.quicksprout.com/2014/05/21/how-to-create-an-seo-friendly-infinite-scrolling-page/

**Comment by bologer** [comment]
Pregenerate next tag on the fly with php: 

```html
<link rel="next" href=/slug#comments-page-2" />
```
Or something similar to this. 

Should think about URL structure.

**Comment by bologer** [comment]
This was already implemented.
