### ISSUE TITLE
После релиза 0.0.66 перестал работать переход к комментариям

### ISSUE THREAD

**Issue by artikus11** [bologer/anycomment.io#267]
Не работает переход к комментариям по анкорам #comments и #respond

**Comment by artikus11** [comment]
@bologer Это ты наверное что-то накрутил))) Заработало)

**Comment by bologer** [comment]
@artikus11 сам в шоке, вчера тестил, не работало, а сегодня уже работает) Может кеш)

**Comment by artikus11** [comment]
@bologer Дак у меня нет кеша) Я все отключил

Магия!
