### ISSUE TITLE
Не работает на woocommerce

### ISSUE THREAD

**Issue by CuteD0d** [bologer/anycomment.io#302]
Не отображаются старие комментарии Woocommerce 3.5.1 в Query Monitor ошибки. На версии 0.0.71 слетает стиль поле woocommerce комментариев улетает в подвал.
![2018-11-12](https://user-images.githubusercontent.com/44075336/48412202-a49bba00-e74c-11e8-9546-00282dc9b032.png)

**Comment by bologer** [comment]
Вы совсем недавно установили плагин? 

Если да, то вероятнее всего пока не было много данных в таблицах. Попробуйте удалить все таблицы с префиксом `anycomment_`, и удалить опцию `anycomment_migration` из `wp_options` и зайти на сайт. Таблицы должны заново создаться.

**Comment by bologer** [comment]
Можно скрин как и что улеает? Чтобы было проще понять

**Comment by CuteD0d** [comment]
Можно в личку написать в телеграме? Предоставлю скриншоты или ссылку на сайт.

**Comment by bologer** [comment]
Да, [сюда](t.me/ateshabaev)
