### ISSUE TITLE
Real time update

### ISSUE THREAD

**Issue by foxrus** [bologer/anycomment.io#310]
Запретить обновление в режиме реального времени для не авторизованных пользователей, чтобы снизить нагрузку на сервер.

**Comment by bologer** [comment]
Тут немного в другом проблема была. Я сделал фикс, посмотрим как будет по производительности в 0.0.73.

**Comment by foxrus** [comment]
Когда выйдет версия 0,0,73?

**Comment by bologer** [comment]
@foxrus вышло уже. Я у себя на блоге буду тестировать, посмотрим результаты. Напишите еще ваши наблюдения, будет интересно узнать.

**Comment by foxrus** [comment]
Это уже другое дело. Протестировал, и нагрузка действительно упала. Спасибо за отличный плагин.

**Comment by foxrus** [comment]
Не хватает дизлайков и смайлов, и был бы идеальный плагин. Когда планируешь добавить?

**Comment by bologer** [comment]
Дислайки и [смайлы](153) уже запланированы. Откройте новый тикет или задайте вопрос в Телеграмме, чтобы задать вопросы. Проблема из этого тикета уже решена.
