### ISSUE TITLE
Опционально включать комментарии для определенных CPT

### ISSUE THREAD

**Issue by Slamik** [bologer/anycomment.io#391]
На сайте для отображения постов используется несколько Custom Post Types.
По умолчанию включение комментариев работает для всех типов постов, что может приводить к ошибкам, как здесь:
![image](https://user-images.githubusercontent.com/9116220/54273154-f3881d80-458d-11e9-828b-88b0a3b8b75c.png)
Это страница автора.

P.S> Из того, что я успел разобрать в коде (исходя из моего уровня), комментарии запускаются на всех страницах, что приводит к ненужной нагрузке.

**Comment by bologer** [comment]
Относится к #356, этот тикет закроем. Далее все в #356 решаем.
