### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by mocart2** [bologer/anycomment.io#413]
Настроил авторизацию через vk и facebook, при нажатии на иконку соцсети выходит ошибка:

{"code":"rest_no_route","message":"\u041f\u043e\u0434\u0445\u043e\u0434\u044f\u0449\u0438\u0439 \u043c\u0430\u0440\u0448\u0440\u0443\u0442 \u0434\u043b\u044f URL \u0438 \u043c\u0435\u0442\u043e\u0434\u0430 \u0437\u0430\u043f\u0440\u043e\u0441\u0430 \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d","data":{"status":404}}

**Comment by bologer** [comment]
Попробуйте пройтись по [этой](https://plugin.anycomment.io/otladka-anycomment-chastye-problemy-polzovatelej/) статье, обычно проблема состоит из чего-то там описанного. Чаще всего с такой проблемой ко мне обращаются, когда у пользователя стоит плагин блокируются REST API, например Clearfy. Или например плагин оптимизации в котором есть опция разрешающая REST API только авторизованным пользователям.

**Comment by mocart2** [comment]
> Попробуйте пройтись по [этой](https://plugin.anycomment.io/otladka-anycomment-chastye-problemy-polzovatelej/) статье, обычно проблема состоит из чего-то там описанного. Чаще всего с такой проблемой ко мне обращаются, когда у пользователя стоит плагин блокируются REST API, например Clearfy. Или например плагин оптимизации в котором есть опция разрешающая REST API только авторизованным пользователям.

Согласно инструкции, нужно, чтобы "Настройки постоянных ссылок" было "Название записи" у меня же стоит "простые ссылки", если меняю, у меня не открываются записи (так как ссылки меняются) как этого можно избежать? (nginx)

**Comment by bologer** [comment]
@mocart2 в этом обновлении не получится это добавить, запланирую на следующее

**Comment by bologer** [comment]
@mocart2 сегодня выйдет обновление исправляющее эту проблему.

Еще раз спасибо, что сообщили о ней!
