### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by mocart2** [bologer/anycomment.io#415]
Ошибка при авторизации через любую соцсеть (vk,fb):
AnyComment 0.0.93
wp .5.2.3
PHP 7.3.9
<details>
`<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed 'CURLOPT_CONNECTTIMEOUT' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_MAXREDIRS - assumed 'CURLOPT_MAXREDIRS' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLINFO_HEADER_OUT - assumed 'CURLINFO_HEADER_OUT' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_ENCODING - assumed 'CURLOPT_ENCODING' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Warning</b>:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' (this will throw an Error in a future version of PHP) in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php</b> on line <b>245</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Hybridauth\HttpClient\curl_init() in /var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/HttpClient/Curl.php:115
Stack trace:
#0 /var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(476): Hybridauth\HttpClient\Curl-&gt;request('https://api.vk....', 'POST', Array, Array)
#1 /var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(399): Hybridauth\Adapter\OAuth2-&gt;exchangeCodeForAccessToken('2db7a3d8631cecf...')
#2 /var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(306): Hybridauth\Adapter\OAuth2-&gt;authenticateFinish()
#3 /var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Hybridauth.php(103): Hybridauth\Adapter\OAuth2-&gt;authenticate()
#4 /var/www/mysite.ru/wp-content/plugins/anycomment/includes/Rest/AnyCommentSocialAuth.php(423): Hybridauth\Hybridauth-&gt;authenticate('Vkontakte in <b>/var/www/mysite.ru/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/HttpClient/Curl.php</b> on line <b>115</b><br />`</details>

**Comment by bologer** [comment]
Здравствуйте, 
У вас не установлен cURL на вашем хостинге/сервере.
