### ISSUE TITLE
BuddyPress and mentions integration

### ISSUE THREAD

**Issue by deekosta** [bologer/anycomment.io#422]
Are there any plans to integrate AnyComment with BuddyPress, and to begin supporting @mentions? 

AnyComment is the best, fastest self-hosted comment alternative IMO -- cleanest looking, fastest, etc. However, the lack of these features makes it difficult to integrate with a front-end dash like BuddyPress. 

My goal is to put user bookmarks, authored content, bookmarks, comments, mentions, and private mentions all in one place. I'd love to use AnyComment as my commenting system!

**Comment by bologer** [comment]
Hello, @deekosta, 

Sounds good to me. Is there any native implementation of mentions in BuddyPress?

**Comment by deekosta** [comment]
There is. It works with the native commenting system and one(outdated) plugin self-hosted comment system I've found. 

In the native system, when you type "@", you get a little popup like you do here on Github, and live search of usernames. The other comment plugin I mentioned(Deeper Comments), the popup doesn't appear, but the mention notification does appear in BuddyPress anyway.

In AnyComment, you don't get that popup, and the mention notification doesn't show up in BuddyPress, even with the @name manually typed properly.

**Comment by bologer** [comment]
Hello, 
We won't include pop-up for searching users by `@` sign, but notification would be added on 0.0.99 version.

**Comment by bologer** [comment]
@deekosta Hi, `@` mentions would be part of 0.0.99 release.
