### ISSUE TITLE
403 Forbidden Error Page then try add comment

### ISSUE THREAD

**Issue by evgrezanov** [bologer/anycomment.io#432]
403 Forbidden Error Page

If you arrived here due to a search or clicking on a link click your Browser's back button to return to the previous page. Thank you.

**Comment by bologer** [comment]
Привет, это происходит при авторизации?

**Comment by evgrezanov** [comment]
> Привет, это происходит при авторизации?

Привет! Да, при попытке авторизоватся через яндекс, вконтакте или одноклассники

**Comment by evgrezanov** [comment]
Стоял какой-то плагин для безопастности - удалил его, перезаписал . htaccess - все заработало
