### ISSUE TITLE
Getting warning when login with Google account!

### ISSUE THREAD

**Issue by anguschang007** [bologer/anycomment.io#442]
https://prnt.sc/ralcjn

The plugin is getting a warning when trying to login with a Google account! It seems that the plugin is trying to use some sensitive or restricted data! How to fix the problem? Is it a must to get Google's verification?

**Comment by bologer** [comment]
Hi, where does this error happen? On your website? Or on our demo page?

**Comment by bologer** [comment]
Hi, 
I'm closing this as I can't reproduce it.
