### ISSUE TITLE
Critical error when I try to flush the cache

### ISSUE THREAD

**Issue by Cerverox95** [bologer/anycomment.io#443]
Whenever I try to flush the cache (from the "tools" section), I get a critical error in my webpage.

![Screenshot_1](https://user-images.githubusercontent.com/61958849/76183929-d12cde00-61a8-11ea-911f-3570d591dfc8.jpg)

It triggers with the two buttons on that page ("Flush All" and "Flush Comments").

By the way, I tried on two different PHP versions (5.6 and 7.3); and even with two totally different language setups (English and Spanish), but issue continues.

**Comment by bologer** [comment]
Would be fixed in v0.1, see https://github.com/bologer/anycomment.io/pull/441
