### ISSUE TITLE
Saving Changes

### ISSUE THREAD

**Issue by hirenshah** [bologer/anycomment.io#456]
When saving changes for any of the options under Settings, it always reloads to the Generic section.  It would be better if it stayed on the section the user was editing.

I'm currently playing around with CSS, and pressing Save here:
![Annotation 2020-04-08 033234](https://user-images.githubusercontent.com/418112/78738381-a9689b80-7949-11ea-83c4-e866d997745a.png)
(you can see the other issue I raised - the Editor has content but it isn't initially visible)

Reloads to this:
![Annotation 2020-04-08 033256](https://user-images.githubusercontent.com/418112/78738383-aa013200-7949-11ea-8601-378dbf947596.png)

**Comment by bologer** [comment]
Hi, 
Yeah it could be improved. Will take a look at it :)
