### ISSUE TITLE
Global Text Colour

### ISSUE THREAD

**Issue by hirenshah** [bologer/anycomment.io#457]
The Global Text Colour setting shouldn't apply to the Editor text.  The Editor text should have a separate setting.

My website has a dark theme, so I set the Global Text Colour to #f2f2f2.  The Editor text then looks like this:
![Annotation 2020-04-08 033857](https://user-images.githubusercontent.com/418112/78738727-7ffc3f80-794a-11ea-881d-9e9606e7f8a9.png)

Had to define this to cater for it:
```
.ql-editor {
  color: #1A1A1A;
}
```

**Comment by bologer** [comment]
Hi,
Good find, will fix it soon.

**Comment by hirenshah** [comment]
This one I would say is an **enhancement** rather than a _bug_ lol 🤣

**Comment by bologer** [comment]
> This one I would say is an enhancement rather than a bug lol 🤣

It depends how you look at it. The logic didn't cover it, but should've, so I consider it as bug. 

I've currently hardcoded dark color for comment editor. It would be part of 0.1.28 release. 

This is done on purpose. We have plans to move away from design options (or remove them completely), so I didn't want to add new option for editor color only.

At this point, the color of the editor and text inside can be controller via simple CSS rule.
