### ISSUE TITLE
Комментарии к разным постам на одной странице

### ISSUE THREAD

**Issue by bayda-wa** [bologer/anycomment.io#466]
Просьба - реализовать возможность отображения комментариев на одной странице к разным постам. К примеру, чтобы на странице был список постов и под каждым был список комментариев и возможность оставить комментарий для каждого поста отдельно. Спс

**Comment by mihdan** [comment]
Я так понимаю, нужно расширить стандартный шорткод, чтобы он генерил разные ID для контейнеров и все с этим связанное.

**Comment by bologer** [comment]
Я уже занялся реализацией, предполагаю, что получится выпустить в сегодняшнем обновлении. Docs - https://github.com/bologer/anycomment.io/wiki/Client-side

**Comment by bologer** [comment]
Но временно нужно использовать без шорткода, вставкой кода напрямую: 

```html
<div id="anycomment-root"></div>
<script type="text/javascript">
    AnyComment = window.AnyComment || [];
    AnyComment.WP = AnyComment.WP || [];
    AnyComment.WP.push({
        root: 'anycomment-root',
        postId: 1,
    });
</script>
```

Где `postId`, это ID поста коментарии которого нужно загрузить. Кроме этого, нужно иметь в ввиду, чтобы на странице присутствовал `window.anyCommentApiSettings`.
