### ISSUE TITLE
Reinit?

### ISSUE THREAD

**Issue by m-pokrovskii** [bologer/anycomment.io#476]
Hi. Thanks for the awesome plugin. Any chance that it has a way to reinit comments? I load the whole page by ajax and need to reinit comments. Thanks.

**Comment by bologer** [comment]
Sorry, could you please give a bit more info what you mean by init? Maybe specific use case, thanks.

**Comment by m-pokrovskii** [comment]
I do load part of the page with the comments. When I insert the data, the
comments does not load. Neither comments or comments form. Only empty
container and inline script for kick-starting. But firing this script do
nothing. Hope It does make sense for you.

**Comment by bologer** [comment]
I see, I will add it. 

It should be part of the release I plan to have today. 

Thank you for your comment.

**Comment by bologer** [comment]
This should be already implemented, see [docs](https://github.com/bologer/anycomment.io/wiki/Client-side#programmatically-initiate-comments).
