### ISSUE TITLE
Запрос на улучшение: бан пользователя

### ISSUE THREAD

**Issue by codemotion** [bologer/anycomment.io#478]
В WordPress совершенно убогая система бана (в настройках Обсуждения общий список стоп-слов, IP-адресов, юзернеймов). Хотелось бы иметь возможность банить конкретного пользователя, по IP или же по логину/email.

Чтобы при просмотре комментариев можно было бы забанить сразу отдельных комментаторов, нарушающих правила сообщества.

**Comment by bologer** [comment]
Добрый день, 
Спасибо за тикет, дубликат #70.
Я добавил туда ваши комментарии, обязательно реализуем.
