### ISSUE TITLE
Проблемы с формой комментария

### ISSUE THREAD

**Issue by ginnogin** [bologer/anycomment.io#484]
Добрый день! Снова столкнулась с поломкой формы комментария. В прошлый раз удалось решить ее подключением к AnyComment.Cloud, что делать сейчас - не знаю. Как видно, все функции для написания комментария слились в одном месте, а также исчезли иконки для входа через соц.сети.
Еще немного информации для разрешения проблемы:
AnyComment версия: 0.1.29
WordPress версия: 5.4.2
Если понадобится доп.информация, готова предоставить (с плагина скачан архив anycomment-debug).
![2020-08-01_17-06-02](https://user-images.githubusercontent.com/69081922/89104262-a6297c00-d420-11ea-8d64-ebed6aabe1e3.png)

**Comment by bologer** [comment]
Добрый день, 
Эта репозитория только для пользователей, которые пользуются плагином. 
Пишите на support@anycomment.io, если вопрос связан с сервисом. 

Но, попробуйте сбросить кеш браузера.

**Comment by ginnogin** [comment]
Так я и есть пользователь плагина, он у меня на сайте стоит, вот и проблема эта выскочила там)
Сброс кэша не помогает, т.к. данная проблема видна на всех устройствах.
Спасибо, напишу на е-мейл тогда, побольше информации направлю. Надеюсь, разберемся.

**Comment by bologer** [comment]
@ginnogin Вы уже написали? Я не вижу обращения. 
Можете указать ссылку где происходит проблема?
