### ISSUE TITLE
Ошибка после активации

### ISSUE THREAD

**Issue by AlexeyBalin** [bologer/anycomment.io#494]
Подробности ошибки
===================================
Ошибка с типом E_ERROR возникла на строке 37 файла /var/www/domains/***.ru/public_html/wp-content/plugins/anycomment/includes/Cache/UserCache.php. Сообщение об ошибке: Uncaught Error: Call to a member function getItem() on null in /var/www/domains/***.ru/public_html/wp-content/plugins/anycomment/includes/Cache/UserCache.php:37
Stack trace:
#0 /var/www/domains/***.ru/public_html/wp-content/plugins/anycomment/includes/Rest/AnyCommentSocialAuth.php(965): AnyComment\Cache\UserCache::getAvatar('32cfac4093c80b5...')
#1 /var/www/domains/***.ru/public_html/wp-content/plugins/anycomment/includes/AnyCommentAvatars.php(52): AnyComment\Rest\AnyCommentSocialAuth::get_user_avatar_url(1)
#2 /var/www/domains/***.ru/public_html/wp-includes/class-wp-hook.php(289): AnyComment\AnyCommentAvatars->override_avatar_globally('

**Comment by bologer** [comment]
Ошибку уже исправили, спасибо
